package id.infinitelearning.KotlinSubmission.exercise4

import java.io.IOException
import java.nio.file.Files
import java.nio.file.Paths

fun main() {
    var nama = true
    try {
        println("Nama kamu adaa alysa ? $nama")
    } catch (e: ArithmeticException) {
        println("Terjadi kesalahan")
    }
}
    /**
     * Buatlah contoh code penggunaan try catch untuk menangani suatu kasus sesuai keinginan teman-teman
     *
     */
    // Buat di bawah sini
